services:
  warehouseapi:
    build:
      context: .
      dockerfile: WarehouseAPI/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Warehouse;User Id=sa;Password=Passw0rd!234;TrustServerCertificate=True;
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Passw0rd!234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Passw0rd!234", "-Q", "select 1"]
      interval: 10s
      retries: 15
      timeout: 5s
      start_period: 60s

volumes:
  sql_data: